### ISSUE TITLE
Configurar análise do SonarQube/ SonarCloud

### ISSUE THREAD

**Issue by romeuleite** [luissimas/ES2_2023-2_prometheus#19]

**Comment by luissimas** [comment]
Configuramos o SonarQube localmente usando Docker e seguindo as [instruções](https://docs.sonarsource.com/sonarqube/latest/try-out-sonarqube/). Usamos o [ngrok](https://ngrok.com/) para expor a porta local para os demais membros do grupo.

![image](https://github.com/luissimas/ES2_2023-2_prometheus/assets/41878330/d34483f2-e205-4b91-9626-86384f92c224)
![image](https://github.com/luissimas/ES2_2023-2_prometheus/assets/41878330/80f29e85-360c-4db4-8934-22ed6109dcb5)
